backend:
  name: test-repo
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
local_backend: true # run npx netlify-cms-proxy-server for local testing
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown"}
          - label: 'Cats'
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string"}
              - { label: "Description", name: "description", widget: "text"}
  - label: "Partner Universities"
    name: "partners"
    folder: "content/partners"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Country", name: "country", widget: "string" }
      - { label: "Location", name: "location", widget: "map" }
      - { label: "Popup Body", name: "body", widget: "markdown" }